# Generated by Django 5.2.6 on 2025-09-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passenger_home_address_passenger_passenger_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passenger_id',
        ),
    ]
